### ISSUE TITLE
Julian weeks should be computed differently 

### ISSUE THREAD

**Issue by tmcd82070** [tmcd82070/CAMP_RST#1]
For summary "by weeks", weeks need to be defined as Julian weeks.  Julian weeks, as defined for this project, will be 7 day intervals starting on January 1, not work weeks defined by Sunday - Saturday.  That is, week 1 will always be 1 - 7 January regardless of the day of the week 1 January falls on, week 2 will be 8 - 14 January, etc. 

![fix8](https://cloud.githubusercontent.com/assets/4823244/3927258/4116e1f0-23f9-11e4-8364-7c07cf84327b.png)

**Comment by jasmyace** [comment]
Resolved as of last release of May 15, 2015
