### ISSUE TITLE
"Summarize daily catches" routine

### ISSUE THREAD

**Issue by MikeBanach** [tmcd82070/CAMP_RST#12]
Mike Banach comment:

In the past there was a routine for "Summarize daily catch".  It's gone now.

When it was around it sometimes showed only Chinook, sometimes all species.  The last time I checked was spring 2013, and it was all species at that time.

If it comes back, I think it would be most useful to provide summaries for all species, not just for Chinook.  The Chinook data will be there in the CSV.

**Comment by jasmyace** [comment]
Updated as part of May 15, 2015 release.
