### ISSUE TITLE
Output folders

### ISSUE THREAD

**Issue by MikeBanach** [tmcd82070/CAMP_RST#14]
Mike Banach comment:

Analysis output is all piled in the same directory with file names that include several pieces of information, including a time stamp.  Run more than one analysis and things get very very messy immediately if you don't remember to move or delete files before running a second analysis routine.

I think a valuable modification that would be very easy to implement is to make a new directory under "Outputs" and put the new files in that new directory instead of in "Outputs" itself.  The new directory names could be just the time stamp.  Or better, it could be a name based on the selection made by the user plus the time stamp.  In this way people could much more easily keep track of and manage all the files generated.  So the directories under "Outputs" might look something like shown below.  Then people can easily get to what they want and also easily and safely delete exactly what they want to delete.

Estimates production by life stage and run 2014-08-18_11-21-56
Estimates production by life stage and run 2014-08-18_13-15-52
Estimates production by life stage and run 2014-08-19_08-37-21
Estimates production for ONE run 2014-08-18_11-24-03
Estimates production for ONE run 2014-08-18_13-19-26
Estimates production for ONE run 2014-08-19_08-42-06
View all catch records 2014-08-19_08-47-31
etc.

I would continue to include the time stamp in the file names.  I think those are useful if a file is moved or copied.

By the way, I don't know why those items in the list say "Estimates" with the 's' at the end.  To me it should be "Estimate production ..." not "Estimates production ..."

**Comment by jasmyace** [comment]
Not an item of focus in the current work, as directed by Doug.
