### ISSUE TITLE
How does change in date affect production estimates?

### ISSUE THREAD

**Issue by tmcd82070** [tmcd82070/CAMP_RST#16]
From Doug, 1 Apr 2014:

On a different note, I accidentally ran two queries to develop production estimates for Caswell State Park on the Stanislaus River.  I used your 3/21/2014 R code on both quires and used the same Stanislaus River CAMP.mdb file.  The queries I used accidently used different start and end dates; those quires produced different monthly salmon production estimates.  I then ran 2 more quires using another set of start and end dates.  The attached excel file provides the production summaries based on the 4 combinations of start and end dates I specified.  The dates trapping actually occurred during the field season are listed at the top of the workbook.

 

I especially noticed the lack of uniformity in some of the April production estimates, although some of the other #s varied as well.   Specifying different start dates before the beginning of the field season and that occur after the end of the field season does not appear to affect the production estimates, but changing the end date before the end of the field season does change the production estimates.  I would not expect that such a change would affect a monthly production estimate when that monthly production estimate reflects an entire month’s worth of sampling, i.e., its not like a partial April production estimate was the problem.  Can you explain the observation I have?  Thanks for your thoughts.

**Comment by jasmyace** [comment]
Assuming this has been resolved via the May 15, 2015 release.
