### ISSUE TITLE
Kerrie issues

### ISSUE THREAD

**Issue by tmcd82070** [tmcd82070/CAMP_RST#17]
Doug,

Just a few possible errors I noticed while preparing the data for import into our database:

1. upper95pctCI for Feather River/Herringer Riffle/Spring run/2005/5-31-2005

2. upper95pctCI for Feather River/Herringer Riffle/Spring run/2005/5-1-2005

3. Passage and upper95pctCI or Feather River/Sunset Pumps/Spring run/2007/5-31-2007

4. upper95pctCI for Feather River/Sunset Pumps/Spring run/2009/5-31-2009

5. Fall.upper95pctCI for American River/Watt Avenue/Life stage/fry/2012-13; value is listed as 5,389,780,606

6. Fall.upper95pctCI for Feather River/Herringer Riffle/Life stage/fry/2011-12; value is listed as 3,168,742,176

Thanks!!
-Kerrie

**Comment by jasmyace** [comment]
Redundancy with known upper-bootstrapped-confidence-interval problem.
