### ISSUE TITLE
Different results on two runs

### ISSUE THREAD

**Issue by tmcd82070** [tmcd82070/CAMP_RST#18]
From Mike Banach, 28 Mar 14:

When I run "Export non-Chinook catch records" I get the results shown in the
"Export non-Chinook catch records - 1st run" directory.

When I then immediately run "Export non-Chinook catch records" again I get the results shown in the
"Export non-Chinook catch records - 2nd run" directory.

See zip file attached to Mike's email dated 28 Mar 14

**Comment by jasmyace** [comment]
Assuming this is resolved as of May 15, 2015 release.
