### ISSUE TITLE
SOW 2 - Task 2.7:  Update Export non-Chinook Catch Records Report

### ISSUE THREAD

**Issue by jasmyace** [tmcd82070/CAMP_RST#29]
For the "Export non-Chinook catch records" report, revise the PNG legend so it reflects the number of individuals of each non-salmon species caught.

**Comment by jasmyace** [comment]
Is this what you had in mind?

![week_american_testing_2013-10-01_2014-09-29_bycatch_pie](https://cloud.githubusercontent.com/assets/9057972/11845238/2d7b0786-a3d0-11e5-8530-0dc292500f35.png)

**Comment by jasmyace** [comment]
This update added a line of code on line 37 of program by_catch_table.r, so as to append the counts of each species to its name.

**Comment by dougthreloff** [comment]
Jason:



You are close to addressing the issue with the PNG labeling for non-Chinook
records.



Can you put the numbers after the species name (instead of before)?  Thanks.



Doug



*From:* Jason [mailto:notifications@github.com]
*Sent:* Wednesday, December 16, 2015 7:38 AM
*To:* tmcd82070/CAMP_RST
*Subject:* Re: [CAMP_RST] SOW 2 - Task 2.7: Update Export non-Chinook Catch
Records Report (#29)



Is this what you had in mind?

[image: week_american_testing_2013-10-01_2014-09-29_bycatch_pie]
<https://cloud.githubusercontent.com/assets/9057972/11845238/2d7b0786-a3d0-11e5-8530-0dc292500f35.png>

—
Reply to this email directly or view it on GitHub
<https://github.com/tmcd82070/CAMP_RST/issues/29#issuecomment-165146772>.

**Comment by tmcd82070** [comment]
**Action** Make sure "yes" and "no" Include Data in Analysis records are included.

**Comment by jasmyace** [comment]
![week_american_testing_2013-10-01_2014-09-29_bycatch_pie](https://cloud.githubusercontent.com/assets/9057972/11961523/688b2ea8-a896-11e5-9197-5c5c4f6ce510.png)

Here's another example, run off a different query / database.  Note that the numbers now come after, but some of the text (more than the example above) is truncated.  Do you want me to tinker with font sizes, etc. to try and get things to fit?  

If not, I'll feed this program to the big looper and make sure everything is as expected.  Assuming no issues, this task will then be done.

**Comment by dougthreloff** [comment]
Jason:



If you can easily reduce the font size to avoid the truncated text, yes,
please do that.  Don’t spend more than 5 minutes on revising the graph
legend, however.



I consider this task complete.  Thanks.



Doug



*From:* Jason [mailto:notifications@github.com]
*Sent:* Tuesday, December 22, 2015 9:30 AM
*To:* tmcd82070/CAMP_RST
*Cc:* dougthreloff
*Subject:* Re: [CAMP_RST] SOW 2 - Task 2.7: Update Export non-Chinook Catch
Records Report (#29)



[image: Image removed by sender.
week_american_testing_2013-10-01_2014-09-29_bycatch_pie]
<https://cloud.githubusercontent.com/assets/9057972/11961523/688b2ea8-a896-11e5-9197-5c5c4f6ce510.png>

Here's another example, run off a different query / database. Note that the
numbers now come after, but some of the text (more than the example above)
is truncated. Do you want me to tinker with font sizes, etc. to try and get
things to fit?

If not, I'll feed this program to the big looper and make sure everything
is as expected. Assuming no issues, this task will then be done.

—
Reply to this email directly or view it on GitHub
<https://github.com/tmcd82070/CAMP_RST/issues/29#issuecomment-166680641>.[image:
Image removed by sender.]

**Comment by jasmyace** [comment]
Here is an example of the updated report, with the smaller font.  I will move all the examples to the `For Doug` folder on the `ftp` site.  

![run 47--all_sacramento river_rbdd rst_2012-10-01_2013-09-30_bycatch_pie](https://cloud.githubusercontent.com/assets/9057972/12433234/1d7700a8-bebd-11e5-9bc1-4bd66dac22de.png)

**Comment by dougthreloff** [comment]
Jason:



The by catch pie chart looks great with the smaller font.  Thanks!



Doug



*From:* Jason [mailto:notifications@github.com]
*Sent:* Tuesday, January 19, 2016 1:59 PM
*To:* tmcd82070/CAMP_RST
*Cc:* dougthreloff
*Subject:* Re: [CAMP_RST] SOW 2 - Task 2.7: Update Export non-Chinook Catch
Records Report (#29)



Closed #29 <https://github.com/tmcd82070/CAMP_RST/issues/29>.

—
Reply to this email directly or view it on GitHub
<https://github.com/tmcd82070/CAMP_RST/issues/29#event-519670776>.[image:
Image removed by sender.]
