### ISSUE TITLE
SOW 2 - Task 2.9:  Update Plot Histograms Report

### ISSUE THREAD

**Issue by jasmyace** [tmcd82070/CAMP_RST#31]
For the "Plot histograms of fork length" report, revise the R code so: (1) fork length data from traps where the "Include data in analyses?" = "No" and "Yes" is included in the CSV and the PNG, (2) the X-axis label is not truncated and it spans the width of the X-axis, and (3) the format of the alignment of the X-axis and the bars is not offset.

**Comment by jasmyace** [comment]
I believe I've resolved issues (2) and (3), as itemized above.  Note that the x-axis is not truncated, and it spans the width of the plot region.  

I've included some before and after examples, where "before" indicates how the graph used to look, and how it now looks "after."  In proposing this solution, I emphasized the plotting of the minimum and maximum x-axis values.  Sometimes, the difference between these two values is not divisible by 2, or 3, or whatever, making regular tick marks tied to integers troublesome.  Observe how in the last plot, the ticks "double-up" a bit at the far right (maximum) of the range.  Given the large range of data possibilities this program needs to handle, I think this behavior seems okay.  

I'm not sure I understand the requested update to (1) above, so once that's resolved, I'll then go ahead and throw this program to the big looper program for final testing.



EXAMPLE 1
before
![1beforeweek_american_testing_2013-10-01_2014-09-29_len_freq](https://cloud.githubusercontent.com/assets/9057972/11849970/ed7a1f74-a3e7-11e5-9fd4-a1a9226de11f.png)

after
![1afterweek_american_testing_2013-10-01_2014-09-29_len_freq](https://cloud.githubusercontent.com/assets/9057972/11849974/f3631b3e-a3e7-11e5-9254-ba7c396103ab.png)


EXAMPLE 2
before
![2beforeweek_american_testing_2013-10-01_2014-09-29_len_freq](https://cloud.githubusercontent.com/assets/9057972/11849979/fa59e9d6-a3e7-11e5-8f23-70c2c5c5b5b3.png)


after
![2afterweek_american_testing_2013-10-01_2014-09-29_len_freq](https://cloud.githubusercontent.com/assets/9057972/11849982/fcd2a482-a3e7-11e5-838f-a618c2c6d409.png)


EXAMPLE 3
after only
![afterweek_american_testing_2013-10-01_2014-09-29_len_freq](https://cloud.githubusercontent.com/assets/9057972/11849987/00d0b5c4-a3e8-11e5-8026-f11b20bf69a6.png)

**Comment by dougthreloff** [comment]
Jason:



I think you have address the Task 2.9, items 2 and 3.



In regards to Task 2.9, item 1, my request involves the same suggestion as
I had with task 2.8:  the R code used to produce the CSVs and PNGs should
include salmon where the “Include data in analyses?” = “No” and “Yes”, and
should not be limited to cases where the “Include data in analyses?” =
“Yes”.



Thanks.



Doug



*From:* Jason [mailto:notifications@github.com]
*Sent:* Wednesday, December 16, 2015 10:38 AM
*To:* tmcd82070/CAMP_RST
*Subject:* Re: [CAMP_RST] SOW 2 - Task 2.9: Update Plot Histograms Report
(#31)



I believe I've resolved issues (2) and (3), as itemized above. Note that
the x-axis is not truncated, and it spans the width of the plot region.

I've included some before and after examples, where "before" indicates how
the graph used to look, and how it now looks "after." In proposing this
solution, I emphasized the plotting of the minimum and maximum x-axis
values. Sometimes, the difference between these two values is not divisible
by 2, or 3, or whatever, making regular tick marks tied to integers
troublesome. Observe how in the last plot, the ticks "double-up" a bit at
the far right (maximum) of the range. Given the large range of data
possibilities this program needs to handle, I think this behavior seems
okay.

I'm not sure I understand the requested update to (1) above, so once that's
resolved, I'll then go ahead and throw this program to the big looper
program for final testing.

EXAMPLE 1
before
[image: Image removed by sender.
1beforeweek_american_testing_2013-10-01_2014-09-29_len_freq]
<https://cloud.githubusercontent.com/assets/9057972/11849970/ed7a1f74-a3e7-11e5-9fd4-a1a9226de11f.png>

after
[image: Image removed by sender.
1afterweek_american_testing_2013-10-01_2014-09-29_len_freq]
<https://cloud.githubusercontent.com/assets/9057972/11849974/f3631b3e-a3e7-11e5-9254-ba7c396103ab.png>

EXAMPLE 2
before
[image: Image removed by sender.
2beforeweek_american_testing_2013-10-01_2014-09-29_len_freq]
<https://cloud.githubusercontent.com/assets/9057972/11849979/fa59e9d6-a3e7-11e5-8f23-70c2c5c5b5b3.png>

after
[image: Image removed by sender.
2afterweek_american_testing_2013-10-01_2014-09-29_len_freq]
<https://cloud.githubusercontent.com/assets/9057972/11849982/fcd2a482-a3e7-11e5-838f-a618c2c6d409.png>

EXAMPLE 3
after only
[image: Image removed by sender.
afterweek_american_testing_2013-10-01_2014-09-29_len_freq]
<https://cloud.githubusercontent.com/assets/9057972/11849987/00d0b5c4-a3e8-11e5-8026-f11b20bf69a6.png>

—
Reply to this email directly or view it on GitHub
<https://github.com/tmcd82070/CAMP_RST/issues/31#issuecomment-165204589>.[image:
Image removed by sender.]

**Comment by tmcd82070** [comment]
**Action** Make sure "yes" and "no" Include Data in Analysis records are included.

**Comment by jasmyace** [comment]
Given that Task 2.8 has been completed, the necessary changes for this Task have, in theory, been completed as well.  Output associated with this report, as compiled by the Big Looper, for both `by.lifestage = TRUE` (so that the report breaks out by lifestage) and `by.lifestage = FALSE` (so that the report collapses over lifestage), have been uploaded to the `For Doug` folder for perusal.  

It's worth noting that the current output, in both the `png` and `csv`, doesn't allow for a nice place to differentiate `Fishing` versus `NotFishing` instances, like the new `fishing.status` column I detailed in the update for Task 2.8.  So the `csv` associated with this Task 2.9 update remains unchanged.

**Comment by dougthreloff** [comment]
Jason:



I think you have completed this task.  I will want to do one more
validation exercise after you send me the revised R code to close this
issue out in my mind, but I don’t expect any problems.



Thanks for the clarification on the “It's worth noting that the current
output, in both the png and csv, doesn't allow for a nice place to
differentiate Fishing versus NotFishing instances”.



Doug



*From:* Jason [mailto:notifications@github.com]
*Sent:* Tuesday, January 05, 2016 3:50 PM
*To:* tmcd82070/CAMP_RST
*Cc:* dougthreloff
*Subject:* Re: [CAMP_RST] SOW 2 - Task 2.9: Update Plot Histograms Report
(#31)



Given that Task 2.8 has been completed, the necessary changes for this Task
have, in theory, been completed as well. Output associated with this
report, as compiled by the Big Looper, for both by.lifestage = TRUE (so
that the report breaks out by lifestage) and by.lifestage = FALSE (so that
the report collapses over lifestage), have been uploaded to the For Doug
folder for perusal.

It's worth noting that the current output, in both the png and csv, doesn't
allow for a nice place to differentiate Fishing versus NotFishing
instances, like the new fishing.status column I detailed in the update for
Task 2.8. So the csv associated with this Task 2.9 update remains
unchanged.

—
Reply to this email directly or view it on GitHub
<https://github.com/tmcd82070/CAMP_RST/issues/31#issuecomment-169171764>.[image:
Image removed by sender.]

**Comment by jasmyace** [comment]
It's worth noting that the function that creates the output associated with this Issue pulls its (valid) fishing data via Connie's catch query.  However, in deciding to account for half-cone operations, we updated the catch function, which calls Connie's catch query.  

The function that makes this report also utilizes that same catch function.  This means that the data going into this report (now) accounts for half-cone operations.  So, before I closed this out, it made sense to make sure that everything still works, since I changed the fundamental query on which it's made.  You should also make sure you're okay with this now accounting for half-cone operations.  

Here is an example, based on the RBDD, 2012-10-01 through 2013-09-01, Spring Run.  This is the same query criteria I've been using.  Note that via the message at the top, no invalid data exists for this query period and run.  You can see that 2,945 + 2,319 = 5,264 fish are included in this display.  However, opening up the Spring baseTable, and summing the numbers in the assignedCatch, unassignedCatch, and halfConeAdj provides 6,436.  This leaves 6,436 - 5,264 = 1,172 missing fish.  

![week_sacramento river_rbdd rst_2012-10-01_2013-09-30_lifestage f_len_freq](https://cloud.githubusercontent.com/assets/9057972/12405429/44b5867e-be01-11e5-8370-cec37ba44f69.png)

Not all caught fish are measured, and to produce this output, some fish ultimately get thrown out, as they clearly cannot be plotted in a plot based on forklength.  Here, the number of tossed fish equals 1,172 fish, and so all fish here are accounted for.  

Note here, in this example, that no invalid fishing data exists for the Spring run.  

The Late Fall run, however, has both valid and invalid fish.  

![week_sacramento river_rbdd rst_2012-10-01_2013-09-30_lifestage f_len_freq](https://cloud.githubusercontent.com/assets/9057972/12405979/18ae9778-be06-11e5-96ee-9c6aed06421e.png)

Here, the fry and smolt provide 218 + 1,199 = 1,417 fish.  However, the Late Fall baseTable indicates that the sum of the assigned fish, unassigned fish, and halfConeAdj fish is 1,554.  But, that 1,554 doesn't include the 5 invalid fish that this plot does.  That 1,559 fish, however, has 142 fish without a recorded fork length, and 1,559 - 142 = 1,417 fish, as the report shows.  So, these appear correct.

**Comment by jasmyace** [comment]
These reports have been generated for all runs and database criteria, as itemized in the Big Looper code.  I have also uploaded them to the `For Doug` folder on the `ftp` site.
