### ISSUE TITLE
Bars in monthly passage graphic incorrectly labeled on x-axis

### ISSUE THREAD

**Issue by tmcd82070** [tmcd82070/CAMP_RST#5]
![fix5](https://cloud.githubusercontent.com/assets/4823244/3926993/8f6e70aa-23f6-11e4-88c3-fbaf5e274921.png)

**Comment by jasmyace** [comment]
Discovered issue was tied to the current of R used in the Platform;  updates the png function are the suspected cause.  Updating base R solved the issue.
