### ISSUE TITLE
Add Mokelumne to Big Loop?

### ISSUE THREAD

**Issue by jasmyace** [tmcd82070/CAMP_RST#51]
Should we add the Mokelumne database to the Big Run Loop?  This would help to identify any errors that the programs may have, specific to this river.  Obviously, however, an error identified here could also potentially appear in any of the other databases.  If so, we would need some criteria to identify periods of interest, namely specific combinations of site, start date, end date, and run.

**Comment by ConnieShannon** [comment]
It would be good to add mokelumne to the big run loop so long as you can issolate and run only data resulting from the RST and only data from 2002 forward.  They also do smolt trapping and the data prior to 2002 hasn't been corrected yet.  If it doesn't work with the big run I can run it individually.

**Comment by jasmyace** [comment]
Nine individual runs have been added to the Big Loop program.  Each of these begin on 12/1 of a particular year, and end on 7/30 of the next.  The first year covers 2005-2006, while the last currently covers 2013-2014.  I suspect, however, that some of these later-year runs aren't ready to be run yet.
