### ISSUE TITLE
Weird Platform error message on new computer with new Windows 10

### ISSUE THREAD

**Issue by jasmyace** [tmcd82070/CAMP_RST#53]
I'm currently unable to run the Platform on a new computer running Windows 10.  The error is as follows:  

![image](https://cloud.githubusercontent.com/assets/9057972/10496669/1bfaee9a-727f-11e5-97cc-a3d33677370b.png)

Note that this appears to be specific to this computer, as Trent, who is using the same version of Windows, is able to compile a randomly chosen report from the Platform with ease.  

I've alerted our IT guy, who will hopefully have some plan of action shortly to remedy.

**Comment by MikeBanach** [comment]
Jason,
    
    Hi Jason.  I'm one of the people who developed the application. 
    This seems like it's an error that should be captured and handled. 
    If this happens again please copy all the debug details and send
    them to me.  To debug it I would also need the database you were
    using, the current R-Interface files, and the sequence of events
    leading to the error.
    
    I can get email attachments of at least 55 MB.  If you would need to
    send something bigger there are other ways we can handle that.
    
    Mike
    
    Michael Banach
StreamNet Fisheries Biologist
Pacific States Marine Fisheries Commission
503-595-3152         mike_banach@psmfc.org
www.streamnet.org

    
      
      On 10/14/2015 1:24 PM, Jason wrote:
    
    
      
      I'm currently unable to run the Platform on a new computer
        running Windows 10. The error is as follows: 
      
      Note that this appears to be specific to this computer, as
        Trent, who is using the same version of Windows, is able to
        compiled a randomly chosen report from the Platform with ease. 
      I've alerted our IT guy, who will hopefully have some plan of
        action shortly to remedy. 
      —
        Reply to this email directly or view it
          on GitHub.

**Comment by jasmyace** [comment]
I fetched the 06 18 2015 version of the Caswell State Park – Stanislaus River CAMP.mdb from the server, and emulated the error previously obtained on a different CAMP.mdb.  

![image](https://cloud.githubusercontent.com/assets/9057972/10524189/77bcc1ec-733b-11e5-835e-1ae15b7af5b6.png)


Note that it says it cannot find file run_R.out.  I made sure it was there before I started;  now, however, that file is gone from folder Outputs.  

Within the Platform, I followed these steps after opening up the application,
1.  Selected "Cramer Fish Sciences" from "Your agency."
2.  Selected "Jenny Melgo" from "Your name."
3.  Selected "Stanislaus River Caswell State Park Rotary Screw Trap" from "Project you will enter data for."
4.  Hit "OK."
5.  Hit "OK."
6.  Hit "Done (Accept data)."
7.  Selected "Tables & Charts."
8.  Selected "Estimates production by life stage and run."
9.  Selected "Caswell State Park" as the site. 
10.  Changed the second date to "8/1/1997."
11.  Hit "GO."

It is at this point, I received the run_R.out error message as indicated above.  The Platform managed to delete out the run_R.out file.  

It's worth nothing that in the interim since you developed the Platform, we updated the underlying R install -- it's probably easiest if I just send over a zip file with the CAMP.mdb for Caswell State Park, the current R install, and the current R-Interface files in their current set-up, i.e., in the correct folders and what not.  With that said, we haven't had an issue with the updated R.  Also, Trent was able to run a report yesterday on his computer, which does use Windows 10.  We can send over his computer info, if it helps.  

Here is info about my computer, if you need it:

![image](https://cloud.githubusercontent.com/assets/9057972/10524758/682cb95a-733e-11e5-86b6-7f249d1ebe91.png)

Finally, the total size of the zip file containing everything is about 66 MB, so let me know what I need to do to get it to you.  I made sure everything in this zip folder works on my old computer with no problem, so it contains the bare minimum necessary to get things to run.  

Let me know if you need anything else.

**Comment by MikeBanach** [comment]
Jason,
    
    You can use this link to send me your zip file:
    https://psmfc.sharefile.com/r-re4b98ece7eb4d92b
    
    Email would probably work, but at 66MB it could take a LONG time for
    all the bits and pieces to show up.
    
    Mike
    
    
    
    
    On 10/15/2015 12:17 PM, Jason wrote:
    
      
      I fetched the 06 18 2015 version of the Caswell State Park –
        Stanislaus River CAMP.mdb from the server, and emulated the
        error previously obtained on a different CAMP.mdb. 
      
      Note that it says it cannot find file run_R.out. I made sure it
        was there before I started; now, however, that file is gone from
        folder Outputs. 
      Within the Platform, I followed these steps after opening up
        the application,
        1. Selected "Cramer Fish Sciences" from "Your agency."
        2. Selected "Jenny Melgo" from "Your name."
        3. Selected "Stanislaus River Caswell State Park Rotary Screw
        Trap" from "Project you will enter data for."
        4. Hit "OK."
        5. Hit "OK."
        6. Hit "Done (Accept data)."
        7. Selected "Tables & Charts."
        8. Selected "Estimates production by life stage and run."
        9. Selected "Caswell State Park" as the site. 
        10. Changed the second date to "8/1/1997."
        11. Hit "GO."
      It is at this point, I received the run_R.out error message as
        indicated above. The Platform managed to delete out the
        run_R.out file. 
      It's worth nothing that in the interim since you developed the
        Platform, we updated the underlying R install -- it's probably
        easiest if I just send over a zip file with the CAMP.mdb for
        Caswell State Park, the current R install, and the current
        R-Interface files in their current set-up, i.e., in the correct
        folders and what not. With that said, we haven't had an issue
        with the updated R. Also, Trent was able to run a report
        yesterday on his computer, which does use Windows 10. We can
        send over his computer info, if it helps. 
      Here is info about my computer, if you need it:
      
      Finally, the total size of the zip file containing everything
        is about 66 MB, so let me know what I need to do to get it to
        you. I made sure everything in this zip folder works on my old
        computer with no problem, so it contains the bare minimum
        necessary to get things to run. 
      Let me know if you need anything else. 
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by jasmyace** [comment]
Okay, the zipped file was uploaded successfully.  Let me know if you need
anything else from me.

On Thu, Oct 15, 2015 at 3:18 PM, Mike Banach <notifications@github.com>
wrote:

>
>
>
>
>
> Jason,
>
> You can use this link to send me your zip file:
> https://psmfc.sharefile.com/r-re4b98ece7eb4d92b
>
> Email would probably work, but at 66MB it could take a LONG time for
> all the bits and pieces to show up.
>
> Mike
>
>
>
>
> On 10/15/2015 12:17 PM, Jason wrote:
>
>
> I fetched the 06 18 2015 version of the Caswell State Park –
> Stanislaus River CAMP.mdb from the server, and emulated the
> error previously obtained on a different CAMP.mdb.
>
> Note that it says it cannot find file run_R.out. I made sure it
> was there before I started; now, however, that file is gone from
> folder Outputs.
> Within the Platform, I followed these steps after opening up
> the application,
> 1. Selected "Cramer Fish Sciences" from "Your agency."
> 2. Selected "Jenny Melgo" from "Your name."
> 3. Selected "Stanislaus River Caswell State Park Rotary Screw
> Trap" from "Project you will enter data for."
> 4. Hit "OK."
> 5. Hit "OK."
> 6. Hit "Done (Accept data)."
> 7. Selected "Tables & Charts."
> 8. Selected "Estimates production by life stage and run."
> 9. Selected "Caswell State Park" as the site.
> 10. Changed the second date to "8/1/1997."
> 11. Hit "GO."
> It is at this point, I received the run_R.out error message as
> indicated above. The Platform managed to delete out the
> run_R.out file.
> It's worth nothing that in the interim since you developed the
> Platform, we updated the underlying R install -- it's probably
> easiest if I just send over a zip file with the CAMP.mdb for
> Caswell State Park, the current R install, and the current
> R-Interface files in their current set-up, i.e., in the correct
> folders and what not. With that said, we haven't had an issue
> with the updated R. Also, Trent was able to run a report
> yesterday on his computer, which does use Windows 10. We can
> send over his computer info, if it helps.
> Here is info about my computer, if you need it:
>
> Finally, the total size of the zip file containing everything
> is about 66 MB, so let me know what I need to do to get it to
> you. I made sure everything in this zip folder works on my old
> computer with no problem, so it contains the bare minimum
> necessary to get things to run.
> Let me know if you need anything else.
> —
> Reply to this email directly or view
> it on GitHub.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tmcd82070/CAMP_RST/issues/53#issuecomment-148523878>.
>



-- 
DWH ATTORNEY WORK PRODUCT / ATTORNEY-CLIENT COMMUNICATIONS


*Jason Mitchell*
*Research Biometrician*


Environmental & Statistical Consultants
200 S. Second Street
Laramie, WY 82070
(307) 721-7342
jmitchell@west-inc.com
www.west-inc.com

*Follow WEST: *Facebook
<http://www.facebook.com/pages/Western%E2%80%90EcoSystems%E2%80%90Technology%E2%80%90WESTInc/125604770807646>
, Twitter <http://twitter.com/WestEcoSystems>, Linked In
<http://www.linkedin.com/company/1458419>, Join our Mailing list
<http://visitor.r20.constantcontact.com/manage/optin/ea?v=001qrD4A3S5xJ5KgMyelH9jyw%3D%3D>

CONFIDENTIALITY NOTICE:  This message and any accompanying communications
are covered by the Electronic Communications Privacy Act, 18 U.S.C. §§
2510-2521, and contain information that is privileged, confidential or
otherwise protected from disclosure.  If you are not the intended recipient
or an agent responsible for delivering the communication to the intended
recipient, you are hereby notified that you have received this
communication in error.  Dissemination, distribution or copying of this
e-mail or the information herein by anyone other than the intended
recipient, or an employee or agent responsible for delivering the message
to the intended recipient, is prohibited.  If you have received this
communication in error, please notify us immediately by e-mail and delete
the original message.  Thank you.

P Please consider the environment before printing.

**Comment by MikeBanach** [comment]
Jason, I suspect the problem is permissions on your machine, because it 
works fine for me on Win10 too.  Please send me your direct email 
address and phone number so we can go through iterations without 
bothering everyone.

Mike

Michael Banach
StreamNet Fisheries Biologist
Pacific States Marine Fisheries Commission
503-595-3152         mike_banach@psmfc.org
www.streamnet.org

**Comment by MikeBanach** [comment]
Jason, you can download a test executable at this link:
    https://psmfc.sharefile.com/d-s57cd24b2d494094a
    
    Copy your CAMPrst directory to a new spot.  Run your test to be sure
    the error happens in the new spot.  Assuming it does, replace
    CAMPrst.exe in this test directory with this new downloaded version
    of the file.  I'm not promising this will run, but I think it will. 
    If it does run, I expect you will get the same error.  All I did
    here was make the path to run_R.out more standard and explicit in a
    couple places.  It should actually have no effect.
    
    Next I will make an executable that will let us ID which line of
    code is throwing the exception.  I'll have that for you in a few
    minutes and you can then test that CAMPrst.exe file.
    
    Mike
    
    Michael Banach
StreamNet Fisheries Biologist
Pacific States Marine Fisheries Commission
503-595-3152         mike_banach@psmfc.org
www.streamnet.org

    
      
      
      On 10/15/2015 12:17 PM, Jason wrote:
    
    
      
      I fetched the 06 18 2015 version of the Caswell State Park –
        Stanislaus River CAMP.mdb from the server, and emulated the
        error previously obtained on a different CAMP.mdb. 
      
      Note that it says it cannot find file run_R.out. I made sure it
        was there before I started; now, however, that file is gone from
        folder Outputs. 
      Within the Platform, I followed these steps after opening up
        the application,
        1. Selected "Cramer Fish Sciences" from "Your agency."
        2. Selected "Jenny Melgo" from "Your name."
        3. Selected "Stanislaus River Caswell State Park Rotary Screw
        Trap" from "Project you will enter data for."
        4. Hit "OK."
        5. Hit "OK."
        6. Hit "Done (Accept data)."
        7. Selected "Tables & Charts."
        8. Selected "Estimates production by life stage and run."
        9. Selected "Caswell State Park" as the site. 
        10. Changed the second date to "8/1/1997."
        11. Hit "GO."
      It is at this point, I received the run_R.out error message as
        indicated above. The Platform managed to delete out the
        run_R.out file. 
      It's worth nothing that in the interim since you developed the
        Platform, we updated the underlying R install -- it's probably
        easiest if I just send over a zip file with the CAMP.mdb for
        Caswell State Park, the current R install, and the current
        R-Interface files in their current set-up, i.e., in the correct
        folders and what not. With that said, we haven't had an issue
        with the updated R. Also, Trent was able to run a report
        yesterday on his computer, which does use Windows 10. We can
        send over his computer info, if it helps. 
      Here is info about my computer, if you need it:
      
      Finally, the total size of the zip file containing everything
        is about 66 MB, so let me know what I need to do to get it to
        you. I made sure everything in this zip folder works on my old
        computer with no problem, so it contains the bare minimum
        necessary to get things to run. 
      Let me know if you need anything else. 
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by MikeBanach** [comment]
This version will give some message boxes before/after each line of
    code that refers to run_R.out.  Run it and let me know the sequence
    of numbers you get, and where the error happens.
    https://psmfc.sharefile.com/d-s741ec524da6487e8
    
    Mike
    
    
    
    On 10/15/2015 4:42 PM, Mike Banach wrote:
    
      
      Jason, you can download a test executable at this link:
      https://psmfc.sharefile.com/d-s57cd24b2d494094a
      
      Copy your CAMPrst directory to a new spot.  Run your test to be
      sure the error happens in the new spot.  Assuming it does, replace
      CAMPrst.exe in this test directory with this new downloaded
      version of the file.  I'm not promising this will run, but I think
      it will.  If it does run, I expect you will get the same error. 
      All I did here was make the path to run_R.out more standard and
      explicit in a couple places.  It should actually have no effect.
      
      Next I will make an executable that will let us ID which line of
      code is throwing the exception.  I'll have that for you in a few
      minutes and you can then test that CAMPrst.exe file.
      
      Mike
      
      Michael Banach
StreamNet Fisheries Biologist
Pacific States Marine Fisheries Commission
503-595-3152         mike_banach@psmfc.org
www.streamnet.org

      
        
        
        On 10/15/2015 12:17 PM, Jason wrote:
      
      
        
        I fetched the 06 18 2015 version of the Caswell State Park –
          Stanislaus River CAMP.mdb from the server, and emulated the
          error previously obtained on a different CAMP.mdb. 
        
        Note that it says it cannot find file run_R.out. I made sure
          it was there before I started; now, however, that file is gone
          from folder Outputs. 
        Within the Platform, I followed these steps after opening up
          the application,
          1. Selected "Cramer Fish Sciences" from "Your agency."
          2. Selected "Jenny Melgo" from "Your name."
          3. Selected "Stanislaus River Caswell State Park Rotary Screw
          Trap" from "Project you will enter data for."
          4. Hit "OK."
          5. Hit "OK."
          6. Hit "Done (Accept data)."
          7. Selected "Tables & Charts."
          8. Selected "Estimates production by life stage and run."
          9. Selected "Caswell State Park" as the site. 
          10. Changed the second date to "8/1/1997."
          11. Hit "GO."
        It is at this point, I received the run_R.out error message
          as indicated above. The Platform managed to delete out the
          run_R.out file. 
        It's worth nothing that in the interim since you developed
          the Platform, we updated the underlying R install -- it's
          probably easiest if I just send over a zip file with the
          CAMP.mdb for Caswell State Park, the current R install, and
          the current R-Interface files in their current set-up, i.e.,
          in the correct folders and what not. With that said, we
          haven't had an issue with the updated R. Also, Trent was able
          to run a report yesterday on his computer, which does use
          Windows 10. We can send over his computer info, if it helps. 
        Here is info about my computer, if you need it:
        
        Finally, the total size of the zip file containing everything
          is about 66 MB, so let me know what I need to do to get it to
          you. I made sure everything in this zip folder works on my old
          computer with no problem, so it contains the bare minimum
          necessary to get things to run. 
        Let me know if you need anything else. 
        —
          Reply to this email directly or view

            it on GitHub.

**Comment by jasmyace** [comment]
I downloaded the new .exe and put it on my desktop.  I then recopied the folder I sent you yesterday, and then, at your request, ran the (old) .exe to make sure the error was still there...and it wasn't -- the program completed.  I never double-clicked / opened your new .exe.  

I then went back to the original folder where I keep everything, and tried it there.  It also worked there as well.  

The only thing I can think of is that a Windows Update happened this morning after I had to restart my computer, and something was pushed along / installed to make everything work.  Windows Update tells me two things were updated yesterday, along with several things the day before -- I suspect one of the two things at the top (in the screenshot below, which maybe you can't see unless you're on GitHub) installed 10/15 had the magic to fix everything.  Depending on how far we want to take this, we could probably uninstall one of these two or the other, to see which one fixes Windows.  

![image](https://cloud.githubusercontent.com/assets/9057972/10542407/3547576a-73d5-11e5-83f6-8b0a399340d1.png)

**Comment by MikeBanach** [comment]
I didn't grow up on a farm, but I still have the philosophy of "if
    it ain't broke don't fix it".  Who cares what it was if the problem
    is now gone.  If the problem reappears we'll worry about it then.
    
    My suspicion is that it was a timing issue.  There are only 3 very
    simple lines of code that refer to that run_R file it couldn't
    find.  I suspect this was a timing issue, and if it does appear
    again we can fix it with a simple loop or additional IF statement.
    
    I'm glad it's working.  Let me know if this or any other problem
    appears in the future.
    
    Mike
    
    
    
    On 10/16/2015 6:13 AM, Jason wrote:
    
    
      
      I downloaded the new .exe and put it on my desktop. I then
        recopied the folder I sent you yesterday, and then, at your
        request, ran the (old) .exe to make sure the error was still
        there...and it wasn't -- the program completed. I never
        double-clicked / opened your new .exe. 
      I then went back to the original folder where I keep
        everything, and tried it there. It also worked there as well. 
      The only thing I can think of is that a Windows Update happened
        this morning after I had to restart my computer, and something
        was pushed along / installed to make everything work. Windows
        Update tells me two things were updated yesterday, along with
        several things the day before -- I suspect one of the two things
        at the top (in the screenshot below, which maybe you can't see
        unless you're on GitHub) installed 10/15 had the magic to fix
        everything. Depending on how far we want to take this, we could
        probably uninstall one of these two or the other, to see which
        one fixes Windows. 
      
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by jasmyace** [comment]
Everything is now working.
