### ISSUE TITLE
General Organization of Current Platform and Its Components

### ISSUE THREAD

**Issue by jasmyace** [tmcd82070/CAMP_RST#59]
Based on the Issue involving the reporting of the "R Version Date Missing," it seems I may not have the most recent version of the Platform.  When I click the "Version" button, I can see that my version is from 9/23/2014.

![image](https://cloud.githubusercontent.com/assets/9057972/12238480/6d5b7522-b841-11e5-8e84-b1abfdd873e6.png)

Within the `ftp` site, I can see the "2014 09 23 RST VB code" version, via its folder.  Is there another place where the newer version "`2015.7.6.1300`" can be found?  A search on the the `ftp` didn't reveal it.  

I wonder if it would be worthwhile to create a folder entitled "`Platform Program and Components`," within which one would find two folders:  "`Current Version`" and "`Historical Versions`."  The "`Current Version`" folder would then have three folders:  one for the current Platform, one for the current R code, and one for the current databases.  The "`Historical Versions`" folder would contain the same, but in some format that makes clear the historical progression of each.  Sometimes, it's useful to be able to go back in time and pull obsolete versions of things.  

Please let me know where the updated version of the Platform is;  hopefully installing it will solve whatever is going on with the current version on my computer.

**Comment by ConnieShannon** [comment]
I put version CAMPRST20150706.zip on the public ftp in folder CAMP Platform this morning.  This is CAMP_rst with pass D@t@shar3.  Instructions are also included. You will need to put a CAMP.mdb in the Data folder.  Note that the platform is rigid in that it expects specific file names in specific locations.  If anything isn't where it expects it breaks.
This is the version Doug and I use.  I have put the most recent copy of the QC application in the data folder.  You will want to open it the first time and direct it to find your CAMP.mdb.  
I have also installed R-Interface2015.06.17. You may want to try running the program with this version first.  If it works, try it with your new R code.  If it breaks...you know where to begin looking for the problem.

**Comment by jasmyace** [comment]
I put this as an issue, if only because when we formulate the documentation, we will not want to write "go to folder `blah2015.06.17` to download the Platform, or the updated R code, or the current version of the databases," and so on.  Otherwise, every time we update something, and name it after that date, the documentation will need to be updated as well.  So, I'm wondering if some other non-date-dependent naming scheme would be worthwhile to develop.

**Comment by jasmyace** [comment]
I want to close this issue.  

In the meantime, keep in mind that using folders and files with dates in their names on the FTP site will create updating issues for the future documentation.  Future folder and file name-changes will, of course, necessitate frequent updates to the documentation.  Streamlining the FTP folders (and filenames) could reduce the frequency of future documentation updates, once it comes online.
