### ISSUE TITLE
Error in Estimating Passage Due to No Required Imputation

### ISSUE THREAD

**Issue by jasmyace** [tmcd82070/CAMP_RST#68]
**(from Doug)**

Can you take a look at the attached R output file and tell me what is causing the R code to abort?  Then give me a thought on whether a solution involves:  (1) a change to the data entry or (2) a change to the R code that may be needed.  If the issue could be resolved by a potential change to operations in the field, please give me a recommendation on what that change might be.
 
See Connie’s email below on where to find the CAMP.mdb if you need to use that as you test things.  Remember that you may need to rename the file from CAMP2012-2015.mdb to CAMP.mdb.

    > site <- 63000
    > taxon <- "161980"
    > min.date <- "2011-09-01"
    > max.date <- "2012-06-30"
    > by <-"day"
    > output.file <- "D:/CAMP/CAMPPlatform/CAMP_RST_HistoricData/CAMP RST Platform/Outputs/run.passage_Knights RST_2016-02-03_13-58-57"
    > ci <- FALSE

    Error in as.POSIXlt.default(x, tz = tz) : 
      do not know how to convert 'x' to class "POSIXlt"
    Calls: F.run.passage ... strftime -> format -> as.POSIXlt -> as.POSIXlt.default
    Execution halted

**Comment by jasmyace** [comment]
In this Knight's Landing example, two traps were operating over a span of several days.  Over that period, there was only one instance of "Not fishing," for a duration of 60 minutes.  Given that imputation only occurs over a "Not fishing" span of 120 minutes, absolutely no imputation is required in the estimation of passage.  

A previous update required the collection of all imputed fish for reporting in the final baseTable.  In this case, because no imputation occurred, there are no imputed fish to incorporate.  The code was not set up to handle this degenerate case of no fish to include.  (To be more correct, the number of fish to include is zero.)  

I will make the small change necessary to incorporate this possibility.  This should be a quick update.

**Comment by ConnieShannon** [comment]
You’re awesome!  The biologist will want to know when the new version will be made available.

**Comment by jasmyace** [comment]
This update would be made available with all the other Task 2 updates;  so in theory, relatively soon.    

Note that if they want numbers sooner, I *believe* they could choose a `trapVisitID` with a small catch, and with a fishing `SampleMinutes` greater than 120 minutes, and then set its includeCatchID to `No`.  In this way, the program would then impute a (small) number, and would complete without error.  In thinking about it, I think they would need to choose two `trapVisitIDs` -- one for each trap.  

Note this can't be the first or last trapping instance however;  in that case, those trapping instances would just be excluded, and not force the queries to insert the necessary "Not fishing."

Hope that makes sense.  Basically, as long as they pick a low-catch day to throw out (for now), for each trap, the R code will impute a correspondingly low number, and then not err.  In this way, the "fake" passage that results should not be too far from the real thing.  

I guess another way to think of it is Krista's solution for the American river, but in reverse.  Instead of adding in bad data to plug a long period of no fishing, I think you could delete good data to force a (small) period of no fishing.

**Comment by ConnieShannon** [comment]
Got it!

**Comment by jasmyace** [comment]
I made this update, and was able to obtain results.  If you ended up doing the hack I described above, and obtained passage estimates, I would be curious to know if my numbers here were similar to yours.  

![image](https://cloud.githubusercontent.com/assets/9057972/13160206/49fe1f6e-d653-11e5-8a02-1e1f4ae7efe1.png)

In the meantime, however, I will close the issue.
