### ISSUE TITLE
In monthly CSV file, re-label 'NumFishMeasured' to clarify meaning

### ISSUE THREAD

**Issue by tmcd82070** [tmcd82070/CAMP_RST#7]
![fix7](https://cloud.githubusercontent.com/assets/4823244/3927086/496278bc-23f7-11e4-8bd8-f5702d446c40.png)

**Comment by jasmyace** [comment]
Updated daily fish CSV to reflect total number of fish measured, plus-counted, imputed, and total.  So this issue is obsolete.
